"""4_order filed added

Revision ID: 3b4302a1dc7c
Revises: d6c14ba7a240
Create Date: 2020-01-31 12:39:54.888455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4302a1dc7c'
down_revision = 'd6c14ba7a240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('order_filed', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movies', 'order_filed')
    # ### end Alembic commands ###
