"""5_order filed added

Revision ID: 6d9e64b17f0e
Revises: 3b4302a1dc7c
Create Date: 2020-01-31 12:50:49.076915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9e64b17f0e'
down_revision = '3b4302a1dc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', sa.Column('order_filed', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
