"""7-permission added to project

Revision ID: 83412d2310e6
Revises: 9acdc1e7b8e7
Create Date: 2020-02-02 15:04:27.906427

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '83412d2310e6'
down_revision = '9acdc1e7b8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_permissions')),
    sa.UniqueConstraint('id', name=op.f('permissions_id_key')),
    sa.UniqueConstraint('permission', name=op.f('permissions_id_key'))
    )
    op.create_table('group_permissions',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('permission_id', postgresql.UUID(), nullable=False),
    sa.Column('group_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_tb_group_permissions_col_group_id')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_tb_group_permissions_col_permission_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_group_permissions')),
    sa.UniqueConstraint('group_id', 'permission_id', name=op.f('group_permissions_id_key')),
    sa.UniqueConstraint('id', name=op.f('group_permissions_id_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
