"""6-group added to project

Revision ID: 9acdc1e7b8e7
Revises: 6d9e64b17f0e
Create Date: 2020-02-02 14:45:14.867927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9acdc1e7b8e7'
down_revision = '6d9e64b17f0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('person_id', postgresql.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_tb_groups_col_person_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_groups')),
    sa.UniqueConstraint('id', name=op.f('groups_id_key')),
    sa.UniqueConstraint('title', name=op.f('groups_id_key'))
    )
    op.create_table('group_users',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('group_id', postgresql.UUID(), nullable=False),
    sa.Column('user_id', postgresql.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_tb_group_users_col_group_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tb_group_users_col_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_group_users')),
    sa.UniqueConstraint('group_id', 'user_id', name=op.f('group_users_id_key')),
    sa.UniqueConstraint('id', name=op.f('group_users_id_key'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_users')
    op.drop_table('groups')
    # ### end Alembic commands ###
