"""2-rating model added

Revision ID: e1a54b4e1ef8
Revises: b57c21d5c66f
Create Date: 2020-01-25 11:37:44.341170

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e1a54b4e1ef8'
down_revision = 'b57c21d5c66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratings',
    sa.Column('creation_date', sa.Integer(), nullable=False),
    sa.Column('modification_date', sa.Integer(), nullable=True),
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('creator', sa.String(), nullable=True),
    sa.Column('modifier', sa.String(), nullable=True),
    sa.Column('movie_id', postgresql.UUID(), nullable=False),
    sa.Column('person_id', postgresql.UUID(), nullable=False),
    sa.Column('overall_rate', sa.Float(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('novel', sa.Float(), nullable=True),
    sa.Column('character', sa.Float(), nullable=True),
    sa.Column('reason', sa.Float(), nullable=True),
    sa.Column('directing', sa.Float(), nullable=True),
    sa.Column('acting', sa.Float(), nullable=True),
    sa.Column('editing', sa.Float(), nullable=True),
    sa.Column('visualization', sa.Float(), nullable=True),
    sa.Column('sound', sa.Float(), nullable=True),
    sa.Column('music', sa.Float(), nullable=True),
    sa.Column('violence_range', sa.Float(), nullable=True),
    sa.Column('insulting_range', sa.Float(), nullable=True),
    sa.Column('sexual_content', sa.Float(), nullable=True),
    sa.Column('unsuitable_wearing', sa.Float(), nullable=True),
    sa.Column('addiction_promotion', sa.Float(), nullable=True),
    sa.Column('horror_content', sa.Float(), nullable=True),
    sa.Column('suicide_encouragement', sa.Float(), nullable=True),
    sa.Column('breaking_law_encouragement', sa.Float(), nullable=True),
    sa.Column('gambling_promotion', sa.Float(), nullable=True),
    sa.Column('alcoholic_promotion', sa.Float(), nullable=True),
    sa.Column('family_subject', sa.Float(), nullable=True),
    sa.Column('individual_social_behavior', sa.Float(), nullable=True),
    sa.Column('feminism_exposure', sa.Float(), nullable=True),
    sa.Column('justice_seeking', sa.Float(), nullable=True),
    sa.Column('theism', sa.Float(), nullable=True),
    sa.Column('bright_future_exposure', sa.Float(), nullable=True),
    sa.Column('hope', sa.Float(), nullable=True),
    sa.Column('iranian_life_style', sa.Float(), nullable=True),
    sa.Column('true_vision_of_enemy', sa.Float(), nullable=True),
    sa.Column('true_historiography', sa.Float(), nullable=True),
    sa.Column('question_1', sa.String(), nullable=True),
    sa.Column('question_2', sa.String(), nullable=True),
    sa.Column('question_3', sa.String(), nullable=True),
    sa.Column('question_4', sa.String(), nullable=True),
    sa.Column('question_5', sa.String(), nullable=True),
    sa.Column('question_6', sa.String(), nullable=True),
    sa.Column('question_7', sa.String(), nullable=True),
    sa.Column('question_8', sa.String(), nullable=True),
    sa.Column('question_9', sa.String(), nullable=True),
    sa.Column('question_10', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_tb_ratings_col_movie_id')),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('fk_tb_ratings_col_person_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tb_ratings')),
    sa.UniqueConstraint('id', name=op.f('ratings_id_key'))
    )
    op.create_unique_constraint(op.f('movies_id_key'), 'movies', ['id'])
    op.drop_constraint('users_id_key', 'users', type_='unique')
    op.create_unique_constraint(op.f('users_id_key'), 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_id_key'), 'users', type_='unique')
    op.create_unique_constraint('users_id_key', 'users', ['username'])
    op.drop_constraint(op.f('movies_id_key'), 'movies', type_='unique')
    op.drop_table('ratings')
    # ### end Alembic commands ###
